// Chinese-English terminology glossary generated from data.js
const termGlossary = [
  { zh: "炼焦工艺", en: "coking process" },
  { zh: "冶金煤", en: "metallurgical coal" },
  { zh: "优质炼焦煤", en: "premium coking coal" },
  { zh: "配煤", en: "coal blend" },
  { zh: "焦炉", en: "coke oven" },
  { zh: "胶质层", en: "plastic layer" },
  { zh: "热塑性区间", en: "thermoplastic range" },
  { zh: "热塑性", en: "thermoplasticity" },
  { zh: "镜质组", en: "vitrinite" },
  { zh: "壳质组", en: "liptinite" },
  { zh: "惰质组显微组分", en: "inertinite macerals" },
  { zh: "大孔", en: "macropore" },
  { zh: "孔隙融合", en: "pore coalescence" },
  { zh: "粘弹性半焦", en: "viscoelastic semi-coke" },
  { zh: "碳化", en: "carbonisation" },
  { zh: "热解", en: "pyrolysis" },
  { zh: "交联结构", en: "cross-linking structures" },
  { zh: "桥键", en: "bridge bonds" },
  { zh: "环状结构", en: "looped structures" },
  { zh: "侧链消除", en: "side-chain elimination" },
  { zh: "芳环缩合", en: "aromatic ring condensation" },
  { zh: "可转移氢自由基", en: "transferable hydrogen radicals" },
  { zh: "芳香结构", en: "aromatic structures" },
  { zh: "脂肪结构", en: "aliphatic structures" },
  { zh: "键断裂", en: "bond cleavage" },
  { zh: "环缩合", en: "ring condensation" },
  { zh: "脱挥发分", en: "devolatilisation" },
  { zh: "挥发分", en: "volatile matters" },
  { zh: "透气性", en: "gas permeability" },
  { zh: "内部气体压力（IGP）", en: "internal gas pressure (IGP)" },
  { zh: "炉墙压力（OWP）", en: "oven wall pressure (OWP)" },
  { zh: "吉氏流动度", en: "Gieseler fluidity" },
  { zh: "平均最大镜质体反射率", en: "mean maximum vitrinite reflectance" },
  { zh: "膨胀压力", en: "Swelling pressure" },
  { zh: "大孔隙率", en: "macroporosity" },
  { zh: "泡沫状热塑性材料", en: "foam-like thermoplastic material" },
  { zh: "固态13C核磁共振", en: "solid-state 13C NMR" },
  { zh: "傅里叶变换红外光谱（FTIR）", en: "Fourier-transform infrared spectroscopy (FTIR)" },
  { zh: "同步辐射红外光谱（Synchrotron IR）", en: "Synchrotron infrared spectroscopy (Synchrotron IR)" },
  { zh: "同步辐射显微CT（SMCT）", en: "Synchrotron micro-CT (SMCT)" },
  { zh: "微型气相色谱", en: "micro-GC" },
  { zh: "三维图像分析（GeoDict）", en: "3D image analysis (GeoDict)" },
  { zh: "扫描电子显微镜（SEM）", en: "scanning electron microscope (SEM)" },
  { zh: "小角X射线散射（SAXS）", en: "small-angle X-ray scattering (SAXS)" },
  { zh: "小角中子散射（SANS）", en: "small-angle neutron scattering (SANS)" },
  { zh: "X射线衍射（XRD）", en: "X-ray diffraction (XRD)" },
  { zh: "电子顺磁共振（EPR）", en: "electron paramagnetic resonance (EPR)" },
  { zh: "热重分析（TGA）", en: "thermogravimetric analysis (TGA)" },
  { zh: "热重-质谱联用（TG-MS）", en: "TG-MS (thermogravimetric-mass spectrometry)" },
  { zh: "芳香簇尺寸", en: "aromatic cluster size" },
  { zh: "质子化芳香碳", en: "protonated aromatic carbons" },
  { zh: "碳键合芳香碳", en: "carbon-bonded aromatic carbons" },
  { zh: "桥键断裂", en: "bridge-bond cleavage" },
  { zh: "焦炭结构", en: "char structure" },
  { zh: "中间塑性体", en: "metaplast" },
  { zh: "软化温度", en: "softening temperature" },
  { zh: "再固化温度", en: "resolidification temperature" },
  { zh: "焦油蒸发", en: "tar vaporisation" },
  { zh: "聚合反应", en: "polymerisation reaction" },
  { zh: "再聚合", en: "repolymerisation" },
  { zh: "芳香缩合", en: "aromatic condensation" },
  { zh: "焦炭反应性指数（CRI）", en: "coke reactivity index (CRI)" },
  { zh: "反应后焦炭强度（CSR）", en: "coke strength after reaction (CSR)" },
  { zh: "半焦", en: "semi-coke" },
  { zh: "煤岩显微组分", en: "coal macerals" },
  { zh: "微孔结构", en: "microporosity" },
  { zh: "温度梯度", en: "temperature gradient" },
  { zh: "移动墙焦炉", en: "movable-wall coke oven" },
  { zh: "双壁加热焦炉", en: "dual-wall-heated coke oven" },
  { zh: "内部气体压力积聚", en: "internal gas pressure build-up" },
  { zh: "孔隙演化", en: "porosity evolution" },
  { zh: "气泡生长与聚并", en: "bubble growth and coalescence" },
  { zh: "膨胀指数", en: "swell index" },
  { zh: "煤阶", en: "coal rank" },
  { zh: "芳香度", en: "aromaticity" },
  { zh: "焦炭基体", en: "coke matrix" },
  { zh: "侧链断裂", en: "side chain cleavage" },
  { zh: "芳环聚合", en: "aromatic ring polymerization" },
  { zh: "芳环融合", en: "aromatic ring fusion" },
  { zh: "键断裂", en: "bond scission" },
  { zh: "气泡形核", en: "bubble nucleation" },
  { zh: "碳堆叠", en: "carbon stacking" },
  { zh: "焦炭基体", en: "char matrix" },
  { zh: "闭孔", en: "closed pore" },
  { zh: "聚并孔隙结构", en: "coalesced pore structure" },
  { zh: "煤阶分类", en: "coal rank classification" },
  { zh: "焦粉", en: "coke breeze" },
  { zh: "稠环体系", en: "condensed ring system" },
  { zh: "互相关分析", en: "cross-correlation analysis" },
  { zh: "脱烷基化", en: "dealkylation" },
  { zh: "掺杂协同效应", en: "doping synergy" },
  { zh: "快速热解", en: "fast pyrolysis" },
  { zh: "流体非挥发性产物", en: "fluid non-volatile product" },
  { zh: "稠合芳环", en: "fused aromatic ring" },
  { zh: "孔隙内截留气体", en: "gas trapped inside pores" },
  { zh: "类石墨烯结构", en: "graphene-like structure" },
  { zh: "均质流体相", en: "homogeneous fluid phase" },
  { zh: "原位测量", en: "in-situ measurements" },
  { zh: "等容膨胀", en: "isometric expansion" },
  { zh: "显微组分组成", en: "maceral composition" },
  { zh: "分子重排", en: "molecular rearrangements" },
  { zh: "开孔", en: "open pore" },
  { zh: "含氧官能团", en: "oxygen functional groups" },
  { zh: "顺磁中心", en: "paramagnetic centers" },
  { zh: "分压梯度", en: "partial pressure gradient" },
  { zh: "渗流通道", en: "percolation pathways" },
  { zh: "多环芳烃(PAHs)", en: "polycyclic aromatic hydrocarbons (PAHs)" },
  { zh: "孔隙连通性", en: "pore connectivity" },
  { zh: "孔隙成核与生长", en: "pore nucleation and growth" },
  { zh: "自由基稳定化", en: "radical stabilization" },
  { zh: "闭环反应", en: "ring closure reaction" },
  { zh: "侧链断裂", en: "side chain scission" },
  { zh: "溶剂溶胀效应", en: "solvent swelling effect" },
  { zh: "剥落现象", en: "spalling phenomenon" },
  { zh: "膨胀指数测试", en: "swelling index test" },
  { zh: "热聚合", en: "thermal polymerization" },
  { zh: "挥发分释放动力学", en: "volatile release kinetics" },
  { zh: "煤碳化", en: "coal carbonization" },
  { zh: "煤化作用", en: "coalification" },
  { zh: "煤塑性特性", en: "coal plastic properties" },
  { zh: "气泡生长机制", en: "bubble growth mechanism" },
  { zh: "脱硫", en: "desulfurization" },
  { zh: "焦炉组", en: "coke oven battery" },
  { zh: "富氢镜质体", en: "perhydrous vitrinite" },
  { zh: "中间相形成", en: "mesophase formation" },
  { zh: "焦油冷凝", en: "tar condensation" },
  { zh: "再聚合动力学", en: "repolymerization kinetics" },
  { zh: "副产品回收", en: "by-product recovery" },
  { zh: "酚类化合物", en: "phenolic compounds" },
  { zh: "焦炭微观结构", en: "coke microstructure" },
  { zh: "渗透率演化", en: "permeability evolution" },
  { zh: "氢化芳香结构", en: "hydroaromatic structures" },
  { zh: "氢分压", en: "partial pressure of hydrogen" },
  { zh: "煤溶胀行为", en: "coal swelling behavior" },
  { zh: "传热梯度", en: "heat transfer gradient" },
  { zh: "热解路径", en: "pyrolysis pathways" },
  { zh: "孔隙网络连通性", en: "pore network connectivity" },
  { zh: "热塑性流动", en: "thermoplastic flow" },
  { zh: "液晶相", en: "liquid crystalline phase" },
  { zh: "压力驱动膨胀", en: "pressure-driven expansion" },
  { zh: "活性显微组分", en: "reactive maceral" },
  { zh: "窄炭化室", en: "narrow coke chamber" },
  { zh: "分子量分布", en: "molecular weight distribution" },
  { zh: "软化熔融阶段", en: "softening-melting stage" },
  { zh: "微结构发育", en: "microtexture development" },
  { zh: "可萃取物", en: "extractable substances" },
  { zh: "流变特性", en: "rheological properties" },
  { zh: "边界层现象", en: "boundary layer phenomena" },
  { zh: "渐进脱挥发分", en: "progressive devolatilization" },
  { zh: "聚合物前驱体", en: "polymeric precursor" },
  { zh: "供氢能力", en: "hydrogen donor capacity" },
  { zh: "焦油残留物", en: "tarry residue" },
  { zh: "软化热塑性区间", en: "softening thermoplastic intervals" },
  { zh: "热膨胀法（TDA）", en: "thermodilatometry (TDA)" },
  { zh: "扫描电镜-能谱分析（SEM-EDS）", en: "SEM-EDS analysis" },
  { zh: "镜质体反射率（Ro）", en: "reflectance of vitrinite (Ro)" },
  { zh: "焦炭水分含量", en: "coke moisture content" },
  { zh: "烷基侧链", en: "alkyl side chains" },
  { zh: "挥发分释放曲线", en: "volatiles release curve" },
  { zh: "逆反应", en: "retrogressive reaction" },
  { zh: "分布活化能模型（DAEM）", en: "distributed activation energy model (DAEM)" },
  { zh: "感应加热焦炉", en: "induction heating coke oven" },
  { zh: "孔隙网络分形维数", en: "porous network fractal dimension" },
  { zh: "孔隙分析滞后回环", en: "hysteresis loop in pore analysis" },
  { zh: "孔隙分形几何", en: "pore fractal geometry" },
  { zh: "无定形碳基体", en: "amorphous carbon matrix" },
  { zh: "各向异性镶嵌结构", en: "anisotropic mosaic" },
  { zh: "β树脂阶段", en: "beta resin stage" },
  { zh: "介孔结构", en: "mesopore structure" },
  { zh: "微孔闭合", en: "micropore closure" },
  { zh: "基体溶胀协同效应", en: "matrix swelling synergy" },
  { zh: "炭化残留物", en: "charring residue" },
  { zh: "自旋-晶格弛豫时间（T1）", en: "spin-lattice relaxation time (T1)" },
  { zh: "纳米级石墨层", en: "nanoscale graphitic layer" },
  { zh: "次烟煤", en: "subbituminous coal" },
  { zh: "挤出物形成", en: "extrudate formation" },
  { zh: "煤溶胀比", en: "coal swelling ratio" },
  { zh: "X射线计算机断层扫描（XRCT）", en: "X-ray computed tomography (XRCT)" },
  { zh: "热解产物分析", en: "pyrolysate analysis" },
  { zh: "烟煤煤阶", en: "bituminous rank" },
  { zh: "羧基脱羧", en: "carboxylic group decarboxylation" },
  { zh: "焦炭超声波检测", en: "ultrasonic testing of coke" },
  { zh: "冶金性能指标", en: "metallurgical property index" },
  { zh: "氦气比重法", en: "He-gas pycnometry" },
  { zh: "澳大利亚炼焦煤", en: "Australian coking coals" },
  { zh: "镜质组含量", en: "vitrinite content" },
  { zh: "吉氏流动度", en: "Gieseler fluidities" },
  { zh: "平均镜质体最大反射率", en: "mean vitrinite maximum reflectance" },
  { zh: "物理化学结构", en: "physicochemical structures" },
  { zh: "配煤组成", en: "coal blend composition" },
  { zh: "元素分析", en: "ultimate analysis" },
  { zh: "工业分析", en: "proximate analysis" },
  { zh: "煤岩分析", en: "petrographic analysis" },
  { zh: "内在水分（IM）", en: "inherent moisture (IM)" },
  { zh: "挥发分（VM）", en: "volatile matter (VM)" },
  { zh: "固定碳（FC）", en: "fixed carbon (FC)" },
  { zh: "平均最大镜质体反射率（MMVR）", en: "mean max vitrinite reflectance (MMVR)" },
  { zh: "惰质组", en: "inertinite" },
  { zh: "双壁加热焦炉", en: "double-wall-heated coke oven" },
  { zh: "4公斤实验室焦炉装置", en: "4 kg laboratory-scale coke oven rig" },
  { zh: "焦化甑", en: "coking retort" },
  { zh: "碳化硅(SiC)加热元件", en: "silicon carbide (SiC) heating element" },
  { zh: "可编程温控系统", en: "programmable temperature control system" },
  { zh: "温度曲线", en: "temperature profiles" },
  { zh: "热电偶", en: "thermocouple" },
  { zh: "压力传感器", en: "pressure sensor" },
  { zh: "焦炭反应器", en: "coke reactor" },
  { zh: "隔热砖", en: "insulation brick" },
  { zh: "石英管", en: "quartz tube" },
  { zh: "取样探针", en: "sampling probe" },
  { zh: "快速淬冷", en: "fast quenching" },
  { zh: "氮气流", en: "nitrogen flow" },
  { zh: "氧化铝板", en: "alumina boards" },
  { zh: "一维传热", en: "one-dimensional heat transfer" },
  { zh: "装料密度", en: "charging density" },
  { zh: "预热炉", en: "preheated oven" },
  { zh: "原位测量", en: "in-situ measurement" },
  { zh: "焦侧", en: "coke side" },
  { zh: "半焦粉末", en: "semi-coke powders" },
  { zh: "同步辐射显微CT(SMCT)", en: "synchrotron micro-CT (SMCT)" },
  { zh: "三维图像分析软件(GeoDict)", en: "3D image analysis software (GeoDict)" },
  { zh: "三维微观结构重构", en: "3D microstructure reconstruction" },
  { zh: "水平切片", en: "horizontal slicing" },
  { zh: "孔隙率(F)", en: "void fraction (F)" },
  { zh: "孔径分布", en: "pore size distribution" },
  { zh: "孔隙分离", en: "isolation of voids" },
  { zh: "布鲁克Vertex 80v傅里叶红外显微镜", en: "Bruker Vertex 80v FTIR microscope" },
  { zh: "光谱曲线拟合", en: "curve-fitting of spectra" },
  { zh: "芳香结构与脂肪结构", en: "aromatic vs. aliphatic structures" },
  { zh: "固态13C核磁共振波谱", en: "solid-state 13C NMR spectroscopy" },
  { zh: "布鲁克AVANCE HD500核磁共振谱仪", en: "Bruker AVANCE HD500" },
  { zh: "魔角旋转(MAS)", en: "magic angle spinning (MAS)" },
  { zh: "接触时间(CP)", en: "contact time (CP)" },
  { zh: "化学位移", en: "chemical shift" },
  { zh: "侧链", en: "side chains" },
  { zh: "芳香碳比例", en: "fraction of aromatic carbons" },
  { zh: "轻质气体分析", en: "light gas analysis" },
  { zh: "微型气相色谱(micro-GC)", en: "micro gas chromatography (micro-GC)" },
  { zh: "固定床热解实验", en: "fixed-bed pyrolysis experiment" },
  { zh: "标准气体混合物校准", en: "calibration with standard gas mixture" },
  { zh: "水冷凝器", en: "water condenser" },
  { zh: "二氯乙烷捕集器", en: "dichloroethane trap" },
  { zh: "热导检测器(TCD)", en: "thermal conductivity detector (TCD)" },
  { zh: "分子筛柱(MS5A)", en: "molecule sieve column (MS5A)" },
  { zh: "极性绘图U(PPU)色谱柱", en: "Polar Plot U (PPU) column" },
  { zh: "中间塑性体形成", en: "metaplast formation" },
  { zh: "煤的热塑性", en: "thermoplasticities of coals" },
  { zh: "塑性层阶段", en: "plastic layer stage" },
  { zh: "温度平台期(水分蒸发)", en: "temperature plateau (moisture evaporation)" },
  { zh: "一维传热梯度", en: "one-dimensional heat transfer gradient" },
  { zh: "等温面", en: "isothermal planes" },
  { zh: "基于实测温度分布的外推法", en: "extrapolation from measured temperature profiles" },
  { zh: "初始软化温度 (IST)", en: "initial softening temperature (IST)" },
  { zh: "固化温度 (ST)", en: "solidification temperature (ST)" },
  { zh: "塑性层厚度", en: "thickness of the plastic layer" },
  { zh: "塑性区不透气边界", en: "impermeable boundary surrounding the plastic region" },
  { zh: "最大内部气体压力 (IGP)", en: "maximum internal gas pressure (IGP)" },
  { zh: "嵌入式压力探针", en: "embedded pressure probes" },
  { zh: "内部气体压力 (IGP) 原位测量", en: "in-situ measurements of IGP" },
  { zh: "煤料中心", en: "centre of the coal charge" },
  { zh: "低渗透性半焦区", en: "low permeability semi-coke zone" },
  { zh: "熔融镜质体", en: "fused vitrinite" },
  { zh: "塑性区间", en: "plastic range" },
  { zh: "配煤对热塑性区间的影响", en: "coal blending effects on thermoplastic range" },
  { zh: "吉泽勒特征温度", en: "Gieseler characteristic temperatures" },
  { zh: "气体扩散路径", en: "gas diffusion pathways" },
  { zh: "最大气体析出速率", en: "maximum gas evolution rate" },
  { zh: "富镜质体煤", en: "vitrinite-rich coal" },
  { zh: "富惰质体煤", en: "inertinite-rich coal" },
  { zh: "延迟软化点", en: "delayed softening point" },
  { zh: "水分向中心迁移", en: "moisture migration to centre" },
  { zh: "压力驱动蒸汽释放", en: "pressure-driven vapor release" },
  { zh: "物理结构转变", en: "transformation of physical structures" },
  { zh: "堆密度控制", en: "bulk density control" },
  { zh: "干法装煤工艺", en: "dry coal charging process" },
  { zh: "焦炭质量参数 (CRI, CSR)", en: "coke quality parameters (CRI, CSR)" },
  { zh: "三元配煤", en: "ternary coal blends" },
  { zh: "焦炭X射线衍射 (XRD)", en: "X-ray diffraction (XRD) of cokes" },
  { zh: "有序焦炭结构", en: "ordered coke structures" },
  { zh: "微聚焦X射线CT", en: "μ–focus X-ray CT" },
  { zh: "同步辐射微CT (SMCT) 分析", en: "synchrotron micro-CT (SMCT) analysis" },
  { zh: "半焦层与塑性层", en: "semi-coke and plastic layers" },
  { zh: "最小粘度", en: "minimum viscosity" },
  { zh: "再固化", en: "resolidification" },
  { zh: "镜质组显微组分熔融", en: "vitrinite maceral fusion" },
  { zh: "粒内孔与粒间孔", en: "intragranular and intergranular pores" },
  { zh: "孔隙率", en: "void fraction (porosity)" },
  { zh: "低流动性富惰质体煤", en: "low fluidity inertinite-rich coal" },
  { zh: "高流动性富镜质体煤", en: "high fluidity vitrinite-rich coal" },
  { zh: "孔隙形核", en: "pore nucleation" },
  { zh: "孤立孔", en: "isolated pore" },
  { zh: "连通孔隙网络", en: "open pore network" },
  { zh: "孔径分布 (PSD)", en: "pore size distribution (PSD)" },
  { zh: "大直径孔洞", en: "large-diameter voids" },
  { zh: "平均直径 (Md)", en: "mean diameter (Md)" },
  { zh: "挥发分滞留", en: "volatile matters entrapment" },
  { zh: "惰质体热稳定性", en: "inertinite thermal stability" },
  { zh: "煤脱挥发分", en: "coal devolatilisation" },
  { zh: "通道状孔隙", en: "channel-like pores" },
  { zh: "填充机制 (镜质体渗透)", en: "filling mechanism (vitrinite infiltration)" },
  { zh: "三维结构参数（Ft、Dn、Vf49.25μm、Mdmax）", en: "3D structural parameters (Ft, Dn, Vf49.25μm, Mdmax)" },
  { zh: "熔合镜质体分子重排", en: "molecular rearrangements of fused vitrinite" },
  { zh: "脂肪族结构键断裂", en: "bond cleavage of aliphatic structures" },
  { zh: "桥键与环状结构", en: "bridge bonds and looped structures" },
  { zh: "交联反应", en: "cross-linking reactions" },
  { zh: "再聚合", en: "re-polymerisation" },
  { zh: "热塑性体形成", en: "thermoplastic mass formation" },
  { zh: "桥键断裂", en: "bridge-bond rupture" },
  { zh: "亚甲基碳（芳键连接/脂键连接）", en: "methylene carbons (aromatic-bonded / aliphatic-bonded)" },
  { zh: "甲基碳（芳键连接/脂键连接）", en: "methyl carbons (aromatic-bonded / aliphatic-bonded)" },
  { zh: "13C核磁共振谱分析", en: "13C NMR spectral analysis" },
  { zh: "同步辐射红外表征", en: "Synchrotron IR characterization" },
  { zh: "ACH2/ACH3比值", en: "ACH2/ACH3 ratio" },
  { zh: "Aar-H/Aal-H比值", en: "Aar-H/Aal-H ratio" },
  { zh: "骨架结构中芳香碳占比（far）", en: "fraction of aromatic carbon in skeletal structures (far)" },
  { zh: "单芳簇总芳香碳数（ωta）", en: "total aromatic carbons per cluster (ωta)" },
  { zh: "单芳簇质子化芳香碳数（ωp）", en: "protonated aromatic carbons per cluster (ωp)" },
  { zh: "单芳簇碳键合芳香碳数（ωc）", en: "carbon-bonded aromatic carbons per cluster (ωc)" },
  { zh: "侧链脱除", en: "side-chain detachment" },
  { zh: "甲烷释放曲线", en: "methane release profile" },
  { zh: "氢气释放曲线", en: "hydrogen release profile" },
  { zh: "环缩合反应", en: "ring condensation reaction" },
  { zh: "芳簇尺寸演变", en: "aromatic cluster size evolution" },
  { zh: "活性大分子结构", en: "reactive macromolecular structures" },
  { zh: "原位电子自旋共振展望", en: "in-situ ESR prospect" },
  { zh: "大孔", en: "macropores" },
  { zh: "大孔数量", en: "number of macropores" },
  { zh: "孔隙结构融合", en: "coalescence of pore structures" },
  { zh: "亚甲基碳", en: "methylene carbons" },
  { zh: "甲基碳", en: "methyl carbons" },
  { zh: "芳香碳", en: "aromatic carbons" },
  { zh: "挥发分释放", en: "volatile matter release" },
  { zh: "焦油生成", en: "tar generation" },
  { zh: "初始软化层", en: "initial softening layer" },
  { zh: "中间塑性层", en: "intermediate plastic layer" },
  { zh: "近再固化层", en: "near-resolidified layer" },
  { zh: "δb+l（单芳簇桥键与环数）", en: "δb+l (bridges and loops per cluster)" },
  { zh: "σ0（单芳簇侧链数）", en: "σ0 (side chains per cluster)" },
  { zh: "ωta（单芳簇总芳香碳数）", en: "ωta (total aromatic carbons per cluster)" },
  { zh: "far（骨架结构中芳香碳占比）", en: "far (fraction of aromatic carbons in skeletal structure)" },
  { zh: "可迁移自由基", en: "transferable radicals" },
  { zh: "膨胀压力", en: "swelling pressure" },
  { zh: "同步辐射显微CT", en: "Synchrotron micro-CT" },
  { zh: "相关系数（r）", en: "correlation coefficient (r)" },
  { zh: "惰质组显微组分", en: "inertinite maceral" },
  { zh: "煤岩显微组分组成", en: "coal maceral composition" },
  { zh: "CSR（反应后焦炭强度）", en: "CSR (coke strength after reaction)" },
  { zh: "未熔合惰质组", en: "unfused inertinite" },
  { zh: "芳香团簇的生长", en: "aromatic cluster development" },
  { zh: "微孔演化阶段", en: "macropore evolution stages" },
  { zh: "中试规模焦炉（CSIRO 400公斤）", en: "pilot-scale coke ovens (400 kg at CSIRO)" },
  { zh: "实际炼焦条件", en: "practical coking conditions" },
  { zh: "半焦区域", en: "semi-coke region" },
  { zh: "三维结构参数", en: "3D structural parameters" },
  { zh: "原位渗透率测量", en: "in-situ permeability measurement" },
  { zh: "传质机制", en: "mass transport mechanisms" },
  { zh: "炉墙压力（OWP）", en: "OWP (oven wall pressure)" },
  { zh: "粘结塑性体", en: "cohesive plastic mass" },
  { zh: "焦炭/半焦转变", en: "coke/semi-coke transition" },
  { zh: "碳结构演变", en: "carbon structure evolution" },
  { zh: "先进分析技术（ESR等）", en: "advanced analytical techniques (ESR, etc.)" },
  { zh: "更强交联结构", en: "stronger cross-linking structures" },
  { zh: "稠合芳环", en: "condensed aromatic rings" },
  { zh: "石墨化", en: "graphitisation" },
  { zh: "焦炭反应性指数（CRI）", en: "CRI (coke reactivity index)" },
  { zh: "配煤机理", en: "coal blending mechanisms" },
  { zh: "焦炭形成方法学", en: "coke formation methodology" },
  { zh: "实验室焦炉验证/商业化", en: "validation / commercialisation of lab-scale coke oven" },
  { zh: "煤性质与焦炭质量的定量关联", en: "quantitative linking of coal properties to coke quality" },
  { zh: "澳大利亚炼焦煤技术营销", en: "technical marketing for Australian coking coal" },
  { zh: "炼焦行为综合研究", en: "integrated study of coking behaviors" },
  { zh: "焦炭质量预测（强度、反应性）", en: "predicting coke quality (strength, reactivity)" },
];

export default termGlossary;
